// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, password_hash, username, created_at, role, disabled_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Username,
		&i.CreatedAt,
		&i.Role,
		&i.DisabledAt,
	)
	return i, err
}
